// <auto-generated />
namespace RetailTradingPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class enterprise_accoounts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(enterprise_accoounts));
        
        string IMigrationMetadata.Id
        {
            get { return "201610240604511_enterprise_accoounts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
